"""Сверка «номер + имя» записи с контактом сделки (задача 5, ТЗ 2026-09-22).

Три точки сверки в движке: путь В (`_step_ensure_contact`, контакт найден, а
не создан), путь Б (`_step_check_contact`, контакт лида воронки 1), `_refresh`
(смена номера у записи с известной сделкой). Путь А не сверяется никогда, а
выключатель `contact_check` гасит все три точки разом.
"""

from datetime import date, datetime
from zoneinfo import ZoneInfo

import pytest

from adminbot.amo import ids
from adminbot.gcal.engine import CalendarEngine, contact_mismatch_text, contact_resolved
from adminbot.gcal.event import EventKind, ParsedEvent
from adminbot.gcal.store import MemoryCalendarStore
from tests.fakes import FakeAmo

MSK = ZoneInfo("Europe/Moscow")
NOW = datetime(2026, 8, 26, 12, 0, tzinfo=MSK)
ORDER_DAY = date(2026, 8, 27)


def an_order(**overrides) -> ParsedEvent:
    fields = dict(
        event_id="evt-1", kind=EventKind.ORDER, order_date=ORDER_DAY,
        phones=("9605379757",), client_name="Юлия", services=("mattress",),
        summary="Сов! Матрас, Юлия",
    )
    fields.update(overrides)
    return ParsedEvent(**fields)


def contact_with_phone(contact_id: int, name: str, phone10: str) -> dict:
    return {"id": contact_id, "name": name,
            "custom_fields_values": [
                {"field_code": "PHONE", "values": [{"value": phone10}]}]}


@pytest.fixture
def amo():
    return FakeAmo()


def build(amo, *, contact_check: bool = True, store=None) -> CalendarEngine:
    return CalendarEngine(amo=amo, store=store or MemoryCalendarStore(now=lambda: NOW),
                          dry_run=False, contact_check=contact_check, now=lambda: NOW)


# --- сверка сама по себе (чистая функция) ---

def test_naташа_and_наталья_are_not_a_mismatch():
    contact = contact_with_phone(1, "Наталья", "9601861933")
    assert contact_mismatch_text("Наташа", "9601861933", contact) is None
    assert contact_resolved("Наташа", "9601861933", contact) is True


def test_ирина_and_наталья_is_a_mismatch():
    contact = contact_with_phone(1, "Наталья", "9601861933")
    text = contact_mismatch_text("Ирина", "9601861933", contact)
    assert text is not None
    assert "Ирина" in text and "Наталья" in text
    assert contact_resolved("Ирина", "9601861933", contact) is False


def test_phone_not_in_contact_is_a_mismatch():
    contact = contact_with_phone(1, "Наталья", "9004445566")
    text = contact_mismatch_text("Наталья", "9601861933", contact)
    assert text is not None
    assert contact_resolved("Наталья", "9601861933", contact) is False


def test_no_record_name_is_not_checked():
    contact = contact_with_phone(1, "Ирина", "9004445566")
    assert contact_mismatch_text(None, "9601861933", contact) is None
    assert contact_resolved(None, "9601861933", contact) is False


def test_autogenerated_contact_name_is_not_checked():
    contact = contact_with_phone(1, "Входящий звонок", "9004445566")
    assert contact_mismatch_text("Наталья", "9601861933", contact) is None
    assert contact_resolved("Наталья", "9601861933", contact) is False


# --- путь В: контакт НАШЁЛСЯ (не создан) ---

async def test_path_c_found_contact_mismatch_is_remembered(amo):
    amo.contacts.append(contact_with_phone(555, "Ирина", "9004445566"))
    engine = build(amo)

    link = await engine.process(an_order())

    assert amo.calls_of("create_contact") == []          # контакт не создавали
    assert link.contact_mismatch is not None
    assert "Юлия" in link.contact_mismatch and "Ирина" in link.contact_mismatch
    assert link.status == "waiting_salesbot"              # цепочка пошла дальше


async def test_path_c_found_contact_matching_is_not_a_mismatch(amo):
    amo.contacts.append(contact_with_phone(555, "Юлия", "9605379757"))
    engine = build(amo)

    link = await engine.process(an_order())

    assert link.contact_mismatch is None


async def test_path_c_newly_created_contact_is_not_checked(amo):
    """Свежесозданный контакт по построению совпадает с записью — сверять нечего."""
    engine = build(amo)

    link = await engine.process(an_order())

    assert amo.calls_of("create_contact")
    assert link.contact_mismatch is None


# --- путь Б: контакт лида воронки 1 ---

async def test_path_b_primary_lead_contact_mismatch_is_remembered(amo):
    amo.add_lead(41400002, ids.PIPELINE_PRIMARY, ids.PRIM_STAGE_DIALOG)
    amo.leads[41400002]["_embedded"] = {"contacts": [{"id": 555}]}
    amo.contacts.append(contact_with_phone(555, "Ирина", "9004445566"))
    engine = build(amo)

    link = await engine.process(an_order())

    assert link.contact_mismatch is not None
    assert link.status == "waiting_salesbot"               # цепочка пошла дальше


async def test_path_b_primary_lead_contact_matching_is_not_a_mismatch(amo):
    amo.add_lead(41400002, ids.PIPELINE_PRIMARY, ids.PRIM_STAGE_DIALOG)
    amo.leads[41400002]["_embedded"] = {"contacts": [{"id": 555}]}
    amo.contacts.append(contact_with_phone(555, "Юлия", "9605379757"))
    engine = build(amo)

    link = await engine.process(an_order())

    assert link.contact_mismatch is None


# --- путь А: не сверяем никогда ---

async def test_path_a_existing_realization_deal_is_never_checked(amo):
    amo.add_lead(41400001, ids.PIPELINE_REALIZATION, ids.REAL_STAGE_CREATED)
    amo.leads[41400001]["_embedded"] = {"contacts": [{"id": 555}]}
    amo.contacts.append(contact_with_phone(555, "Ирина", "9004445566"))   # разошлось бы
    engine = build(amo)

    link = await engine.process(an_order())

    assert link.status == "done"
    assert link.contact_mismatch is None


# --- _refresh: смена номера у записи с известной сделкой ---

async def test_refresh_phone_change_with_known_deal_is_checked(amo):
    amo.add_lead(41400001, ids.PIPELINE_REALIZATION, ids.REAL_STAGE_CREATED)
    amo.leads[41400001]["_embedded"] = {"contacts": [{"id": 555}]}
    amo.contacts.append(contact_with_phone(555, "Юлия", "9605379757"))
    store = MemoryCalendarStore(now=lambda: NOW)
    engine = build(amo, store=store)
    await engine.process(an_order())                       # заводим сделку как обычно

    changed = await engine.process(an_order(phones=("9009991122",)))  # чужой номер

    assert changed.contact_mismatch is not None
    assert changed.status == "done"                          # цепочка не встала


async def test_refresh_phone_change_matching_the_deal_is_not_a_mismatch(amo):
    amo.add_lead(41400001, ids.PIPELINE_REALIZATION, ids.REAL_STAGE_CREATED)
    amo.leads[41400001]["_embedded"] = {"contacts": [{"id": 555}]}
    amo.contacts.append(contact_with_phone(555, "Юлия", "9009991122"))
    store = MemoryCalendarStore(now=lambda: NOW)
    engine = build(amo, store=store)
    await engine.process(an_order())

    changed = await engine.process(an_order(phones=("9009991122",)))

    assert changed.contact_mismatch is None


# --- выключатель ---

async def test_contact_check_disabled_does_nothing_anywhere(amo):
    amo.contacts.append(contact_with_phone(555, "Ирина", "9004445566"))
    amo.add_lead(41400002, ids.PIPELINE_PRIMARY, ids.PRIM_STAGE_DIALOG)
    engine = build(amo, contact_check=False)

    link = await engine.process(an_order())

    assert link.contact_mismatch is None
